/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbonnementRouteImport } from './routes/abonnement'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as DeviseRouteImport } from './routes/devise'
import { Route as EntreprisesRouteImport } from './routes/entreprises'
import { Route as FacturesAchatsRouteImport } from './routes/factures-achats'
import { Route as FacturesVentesRouteImport } from './routes/factures-ventes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MonEntrepriseRouteImport } from './routes/mon-entreprise'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as PersonnesRouteImport } from './routes/personnes'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as RejoindreRouteImport } from './routes/rejoindre'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as TableauDeBordRouteImport } from './routes/tableau-de-bord'
import { Route as TaxesRouteImport } from './routes/taxes'
import { Route as FacturesIdRouteImport } from './routes/factures.$id'
import { Route as FacturesNouvelleRouteImport } from './routes/factures.nouvelle'
import { Route as SuperadminDemandesRouteImport } from './routes/superadmin_.demandes'
import { Route as SuperadminPlansRouteImport } from './routes/superadmin_.plans'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementRoute = AbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviseRoute = DeviseRouteImport.update({
  id: '/devise',
  path: '/devise',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesRoute = EntreprisesRouteImport.update({
  id: '/entreprises',
  path: '/entreprises',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesAchatsRoute = FacturesAchatsRouteImport.update({
  id: '/factures-achats',
  path: '/factures-achats',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesVentesRoute = FacturesVentesRouteImport.update({
  id: '/factures-ventes',
  path: '/factures-ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MonEntrepriseRoute = MonEntrepriseRouteImport.update({
  id: '/mon-entreprise',
  path: '/mon-entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnesRoute = PersonnesRouteImport.update({
  id: '/personnes',
  path: '/personnes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const RejoindreRoute = RejoindreRouteImport.update({
  id: '/rejoindre',
  path: '/rejoindre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordRoute = TableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxesRoute = TaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesIdRoute = FacturesIdRouteImport.update({
  id: '/factures/$id',
  path: '/factures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesNouvelleRoute = FacturesNouvelleRouteImport.update({
  id: '/factures/nouvelle',
  path: '/factures/nouvelle',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminDemandesRoute = SuperadminDemandesRouteImport.update({
  id: '/superadmin_/demandes',
  path: '/superadmin/demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminPlansRoute = SuperadminPlansRouteImport.update({
  id: '/superadmin_/plans',
  path: '/superadmin/plans',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/clients': typeof ClientsRoute
  '/depenses': typeof DepensesRoute
  '/devise': typeof DeviseRoute
  '/entreprises': typeof EntreprisesRoute
  '/factures-achats': typeof FacturesAchatsRoute
  '/factures-ventes': typeof FacturesVentesRoute
  '/login': typeof LoginRoute
  '/mon-entreprise': typeof MonEntrepriseRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/paiements': typeof PaiementsRoute
  '/personnes': typeof PersonnesRoute
  '/profil': typeof ProfilRoute
  '/rapports': typeof RapportsRoute
  '/rejoindre': typeof RejoindreRoute
  '/services': typeof ServicesRoute
  '/superadmin': typeof SuperadminRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/taxes': typeof TaxesRoute
  '/factures/$id': typeof FacturesIdRoute
  '/factures/nouvelle': typeof FacturesNouvelleRoute
  '/superadmin/demandes': typeof SuperadminDemandesRoute
  '/superadmin/plans': typeof SuperadminPlansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/clients': typeof ClientsRoute
  '/depenses': typeof DepensesRoute
  '/devise': typeof DeviseRoute
  '/entreprises': typeof EntreprisesRoute
  '/factures-achats': typeof FacturesAchatsRoute
  '/factures-ventes': typeof FacturesVentesRoute
  '/login': typeof LoginRoute
  '/mon-entreprise': typeof MonEntrepriseRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/paiements': typeof PaiementsRoute
  '/personnes': typeof PersonnesRoute
  '/profil': typeof ProfilRoute
  '/rapports': typeof RapportsRoute
  '/rejoindre': typeof RejoindreRoute
  '/services': typeof ServicesRoute
  '/superadmin': typeof SuperadminRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/taxes': typeof TaxesRoute
  '/factures/$id': typeof FacturesIdRoute
  '/factures/nouvelle': typeof FacturesNouvelleRoute
  '/superadmin/demandes': typeof SuperadminDemandesRoute
  '/superadmin/plans': typeof SuperadminPlansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/clients': typeof ClientsRoute
  '/depenses': typeof DepensesRoute
  '/devise': typeof DeviseRoute
  '/entreprises': typeof EntreprisesRoute
  '/factures-achats': typeof FacturesAchatsRoute
  '/factures-ventes': typeof FacturesVentesRoute
  '/login': typeof LoginRoute
  '/mon-entreprise': typeof MonEntrepriseRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/paiements': typeof PaiementsRoute
  '/personnes': typeof PersonnesRoute
  '/profil': typeof ProfilRoute
  '/rapports': typeof RapportsRoute
  '/rejoindre': typeof RejoindreRoute
  '/services': typeof ServicesRoute
  '/superadmin': typeof SuperadminRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/taxes': typeof TaxesRoute
  '/factures/$id': typeof FacturesIdRoute
  '/factures/nouvelle': typeof FacturesNouvelleRoute
  '/superadmin_/demandes': typeof SuperadminDemandesRoute
  '/superadmin_/plans': typeof SuperadminPlansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnement'
    | '/clients'
    | '/depenses'
    | '/devise'
    | '/entreprises'
    | '/factures-achats'
    | '/factures-ventes'
    | '/login'
    | '/mon-entreprise'
    | '/mot-de-passe-oublie'
    | '/paiements'
    | '/personnes'
    | '/profil'
    | '/rapports'
    | '/rejoindre'
    | '/services'
    | '/superadmin'
    | '/tableau-de-bord'
    | '/taxes'
    | '/factures/$id'
    | '/factures/nouvelle'
    | '/superadmin/demandes'
    | '/superadmin/plans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnement'
    | '/clients'
    | '/depenses'
    | '/devise'
    | '/entreprises'
    | '/factures-achats'
    | '/factures-ventes'
    | '/login'
    | '/mon-entreprise'
    | '/mot-de-passe-oublie'
    | '/paiements'
    | '/personnes'
    | '/profil'
    | '/rapports'
    | '/rejoindre'
    | '/services'
    | '/superadmin'
    | '/tableau-de-bord'
    | '/taxes'
    | '/factures/$id'
    | '/factures/nouvelle'
    | '/superadmin/demandes'
    | '/superadmin/plans'
  id:
    | '__root__'
    | '/'
    | '/abonnement'
    | '/clients'
    | '/depenses'
    | '/devise'
    | '/entreprises'
    | '/factures-achats'
    | '/factures-ventes'
    | '/login'
    | '/mon-entreprise'
    | '/mot-de-passe-oublie'
    | '/paiements'
    | '/personnes'
    | '/profil'
    | '/rapports'
    | '/rejoindre'
    | '/services'
    | '/superadmin'
    | '/tableau-de-bord'
    | '/taxes'
    | '/factures/$id'
    | '/factures/nouvelle'
    | '/superadmin_/demandes'
    | '/superadmin_/plans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementRoute: typeof AbonnementRoute
  ClientsRoute: typeof ClientsRoute
  DepensesRoute: typeof DepensesRoute
  DeviseRoute: typeof DeviseRoute
  EntreprisesRoute: typeof EntreprisesRoute
  FacturesAchatsRoute: typeof FacturesAchatsRoute
  FacturesVentesRoute: typeof FacturesVentesRoute
  LoginRoute: typeof LoginRoute
  MonEntrepriseRoute: typeof MonEntrepriseRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  PaiementsRoute: typeof PaiementsRoute
  PersonnesRoute: typeof PersonnesRoute
  ProfilRoute: typeof ProfilRoute
  RapportsRoute: typeof RapportsRoute
  RejoindreRoute: typeof RejoindreRoute
  ServicesRoute: typeof ServicesRoute
  SuperadminRoute: typeof SuperadminRoute
  TableauDeBordRoute: typeof TableauDeBordRoute
  TaxesRoute: typeof TaxesRoute
  FacturesIdRoute: typeof FacturesIdRoute
  FacturesNouvelleRoute: typeof FacturesNouvelleRoute
  SuperadminDemandesRoute: typeof SuperadminDemandesRoute
  SuperadminPlansRoute: typeof SuperadminPlansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement': {
      id: '/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devise': {
      id: '/devise'
      path: '/devise'
      fullPath: '/devise'
      preLoaderRoute: typeof DeviseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises': {
      id: '/entreprises'
      path: '/entreprises'
      fullPath: '/entreprises'
      preLoaderRoute: typeof EntreprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures-achats': {
      id: '/factures-achats'
      path: '/factures-achats'
      fullPath: '/factures-achats'
      preLoaderRoute: typeof FacturesAchatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures-ventes': {
      id: '/factures-ventes'
      path: '/factures-ventes'
      fullPath: '/factures-ventes'
      preLoaderRoute: typeof FacturesVentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-entreprise': {
      id: '/mon-entreprise'
      path: '/mon-entreprise'
      fullPath: '/mon-entreprise'
      preLoaderRoute: typeof MonEntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnes': {
      id: '/personnes'
      path: '/personnes'
      fullPath: '/personnes'
      preLoaderRoute: typeof PersonnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejoindre': {
      id: '/rejoindre'
      path: '/rejoindre'
      fullPath: '/rejoindre'
      preLoaderRoute: typeof RejoindreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord': {
      id: '/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof TableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxes': {
      id: '/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof TaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures/$id': {
      id: '/factures/$id'
      path: '/factures/$id'
      fullPath: '/factures/$id'
      preLoaderRoute: typeof FacturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures/nouvelle': {
      id: '/factures/nouvelle'
      path: '/factures/nouvelle'
      fullPath: '/factures/nouvelle'
      preLoaderRoute: typeof FacturesNouvelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin_/demandes': {
      id: '/superadmin_/demandes'
      path: '/superadmin/demandes'
      fullPath: '/superadmin/demandes'
      preLoaderRoute: typeof SuperadminDemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin_/plans': {
      id: '/superadmin_/plans'
      path: '/superadmin/plans'
      fullPath: '/superadmin/plans'
      preLoaderRoute: typeof SuperadminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementRoute: AbonnementRoute,
  ClientsRoute: ClientsRoute,
  DepensesRoute: DepensesRoute,
  DeviseRoute: DeviseRoute,
  EntreprisesRoute: EntreprisesRoute,
  FacturesAchatsRoute: FacturesAchatsRoute,
  FacturesVentesRoute: FacturesVentesRoute,
  LoginRoute: LoginRoute,
  MonEntrepriseRoute: MonEntrepriseRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  PaiementsRoute: PaiementsRoute,
  PersonnesRoute: PersonnesRoute,
  ProfilRoute: ProfilRoute,
  RapportsRoute: RapportsRoute,
  RejoindreRoute: RejoindreRoute,
  ServicesRoute: ServicesRoute,
  SuperadminRoute: SuperadminRoute,
  TableauDeBordRoute: TableauDeBordRoute,
  TaxesRoute: TaxesRoute,
  FacturesIdRoute: FacturesIdRoute,
  FacturesNouvelleRoute: FacturesNouvelleRoute,
  SuperadminDemandesRoute: SuperadminDemandesRoute,
  SuperadminPlansRoute: SuperadminPlansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
